import React from "react";
import matter from "gray-matter";
import Link from "next/link";
import { blogPostsArrayFromServer } from "utils/tempBlogUtils";

export default function Index({ posts }) {
    return (
        <div className="wrapper">
            <h1>Home Page</h1>
            <p>
                Click the link below to navigate to a page generated by <code>next-mdx-remote</code>.
            </p>
            <ul>
                {posts.map((post) => (
                    <li key={post.id}>
                        <Link as={`/blog/${post.id}`} href="/blog/[id]">
                            <a>{post.data.title}</a>
                        </Link>
                    </li>
                ))}
            </ul>
            <style jsx>{`
                .wrapper {
                    color: white;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                }
            `}</style>
        </div>
    );
}

export function getStaticProps() {
    const posts = blogPostsArrayFromServer.map((post) => {
        const source = post.markdown;
        const { content, data } = matter(source);

        return {
            content,
            data,
            id: post.id
        };
    });

    return { props: { posts } };
}
